import type { Metadata } from "next";
import { Authenticated } from "@/components";
import { ToastProvider } from "@/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Authenticated>
      <div>
        <ToastProvider />
        {children}
      </div>
    </Authenticated>
  );
}
