"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/redux/providers";
import { ToastContainer } from "react-toastify";
import { ThemeProvider } from "@emotion/react";
import "react-toastify/dist/ReactToastify.css";
import { createTheme } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const theme = createTheme({
  components: {
    MuiRadio: {
      styleOverrides: {
        root: {
          color: "#333399",
          "&.Mui-checked": {
            color: "#333399",
          },
        },
      },
    },
    MuiCheckbox: {
      styleOverrides: {
        root: {
          color: "#333399",
          "&.Mui-checked": {
            color: "#333399",
          },
        },
      },
    },
    MuiTabs: {
      styleOverrides: {
        root: {
          color: "#333399",
        },
        indicator: {
          backgroundColor: "#333399",
          height: "3px",
        },
      },
    },
    MuiTab: {
      styleOverrides: {
        root: {
          fontWeight: "500",
          "&.Mui-selected": {
            color: "#333399",
          },
          "&.Mui-selected:hover": {
            color: "#333399",
          },
          "&:not(.Mui-selected)": {
            color: "black",
          },
        },
      },
    },
    MuiButton: {
      styleOverrides: {
        root: {
          backgroundColor: "#333399",
          boxShadow: "none",
        },
      },
    },
    MuiSwitch: {
      styleOverrides: {
        thumb: {
          color: "#333399",
        },
        track: {
          color: "#333399",
        },
        switchBase: {
          color: "#333399",
        },
      },
    },
  },
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={theme}>
      <Provider>
        <html lang="en">
          <body className={inter.className}>
            {children} <ToastContainer autoClose={5000} />
          </body>
        </html>
      </Provider>
    </ThemeProvider>
  );
}
